<?php $this->render('templates/head.phtml'); ?>


<?php if ($loggedStudent) : ?>

    <?php if ($notify) : ?>
    	<ins style="color: green;">Edit Success!</ins><br>
    <?php endif ?>

    Hello, <?= htmlspecialchars($loggedStudent->getName(), ENT_QUOTES) ?> <?= htmlspecialchars($loggedStudent->getSurname(), ENT_QUOTES) ?>. Want to <a href="registration.php">edit</a>?

    <form method="post" name="logout" action="logout.php?go=/public/index.php">
        <input type="hidden" name="token" value="<?= $token ?>">

        <input type="submit" value="Logout.">
    </form>

<?php endif ?>


<?php $this->render('templates/list.phtml', compact('pager', 'records')); ?>

<?php $this->render('templates/foot.phtml'); ?>