<?php if (isset($pager)) : ?>
	<?php if ($records->count() > 0) : ?>
	    <table>
	        <tr>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('name')) ?>">Name <?= $pager->getSortPostfix('name') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('surname')) ?>">Surname</a> <?= $pager->getSortPostfix('surname') ?></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('gender')) ?>">Gender <?= $pager->getSortPostfix('gender') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('grupNumber')) ?>">Grup Number <?= $pager->getSortPostfix('grupNumber') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('email')) ?>">Email <?= $pager->getSortPostfix('email') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('satScores')) ?>">SAT Scores <?= $pager->getSortPostfix('satScores') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('yearOfBirth')) ?>">Year Of Birth <?= $pager->getSortPostfix('yearOfBirth') ?></a></th>
	            <th><a href="?<?= htmlspecialchars($pager->getSortLinkBy('location')) ?>">Location <?= $pager->getSortPostfix('location') ?></a></th>
	        </tr>

	        <?php foreach ($records as $student) :?>
	            <tr>
	                <td><?= htmlspecialchars(htmlspecialchars($student->getName()) )  ?></td>
	                <td><?= htmlspecialchars($student->getSurname())  ?></td>
	                <td><?= htmlspecialchars($student->getGender())  ?></td>
	                <td><?= htmlspecialchars($student->getGrupNumber())  ?></td>
	                <td><?= htmlspecialchars($student->getEmail())  ?> </td>
	                <td><?= htmlspecialchars($student->getSATscores())  ?></td>
	                <td><?= htmlspecialchars($student->getYearOfBirth())  ?></td>
	                <td><?= htmlspecialchars($student->getLocation())  ?></td>
	            </tr>
	        <?php endforeach; ?>
	    </table>
	<?php else: ?>
	    No records.
	<?php endif; ?>

	<?php if ($pager->getTotalPages() > 1) : ?>
		<div class="pages">
			
			<?php if ($pager->getCurrentPage() != 1) : ?>
				<a href="?<?= htmlspecialchars($pager->getLinkForPage(1)) ?>">[&lt;&lt;]</a>
				<a href="?<?= htmlspecialchars($pager->getLinkForPage($pager->getPreviosPage())) ?>">[&lt;]</a> 
			<?php endif; ?>

			<?php for ($page = 1; $page <= $pager->getTotalPages(); $page++) : ?>
				<?php if ($page != $pager->getCurrentPage()) : ?>
					<a href="?<?= htmlspecialchars($pager->getLinkForPage($page)) ?>">[<?= $page ?>]</a>
				<?php else : ?>
					<a class="currentPage" href="?<?= htmlspecialchars($pager->getLinkForPage($page)) ?>">[<?= $page ?>]</a>
				<?php endif; ?>
			<?php endfor; ?>

			<?php if ($pager->getCurrentPage() != $pager->getTotalPages()) : ?>
				<a href="?<?= htmlspecialchars($pager->getLinkForPage($pager->getNextPage())) ?>">[&gt;]</a>
				<a href="?<?= htmlspecialchars($pager->getLinkForPage($pager->getTotalPages())) ?>">[&gt;&gt;]</a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
