<?php if (isset($pager)) : ?>
	<?php if ($records->count() > 0) : ?>
	    <table>
	        <tr>
	            <th><a href="?<?= $pager->getSortLinkBy('name') ?>">Name <?= $pager->getSortPostfix('name') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('surname') ?>">Surname</a> <?= $pager->getSortPostfix('surname') ?></th>
	            <th><a href="?<?= $pager->getSortLinkBy('gender') ?>">Gender <?= $pager->getSortPostfix('gender') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('grupNumber') ?>">Grup Number <?= $pager->getSortPostfix('grupNumber') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('email') ?>">Email <?= $pager->getSortPostfix('email') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('satScores') ?>">SAT Scores <?= $pager->getSortPostfix('satScores') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('yearOfBirth') ?>">Year Of Birth <?= $pager->getSortPostfix('yearOfBirth') ?></a></th>
	            <th><a href="?<?= $pager->getSortLinkBy('location') ?>">Location <?= $pager->getSortPostfix('location') ?></a></th>
	        </tr>

	        <?php foreach ($records as $student) :?>
	            <tr>
	                <td><?= $student->getName() ?></td>
	                <td><?= $student->getSurname() ?></td>
	                <td><?= $student->getGender() ?></td>
	                <td><?= $student->getGrupNumber() ?></td>
	                <td><?= $student->getEmail() ?> </td>
	                <td><?= $student->getSATscores() ?></td>
	                <td><?= $student->getYearOfBirth() ?></td>
	                <td><?= $student->getLocation() ?></td>
	            </tr>
	        <?php endforeach; ?>
	    </table>
	<?php else: ?>
	    No records.
	<?php endif; ?>

	<?php if ($pager->getTotalPages() > 1) : ?>
		<div class="pages">
			
			<?php if ($pager->getCorrentPage() != 1) : ?>
				<a href="?<?= $pager->getLinkForPage(1) ?>">[&lt;&lt;]</a>
				<a href="?<?= $pager->getLinkForPage($pager->getPreviosPage()) ?>">[&lt;]</a> 
			<?php endif; ?>

			<?php for ($page = 1; $page <= $pager->getTotalPages(); $page++) : ?>
				<?php if ($page != $pager->getCorrentPage()) : ?>
					<a href="?<?= $pager->getLinkForPage($page) ?>">[<?= $page ?>]</a>
				<?php else : ?>
					<a class="correntPage" href="?<?= $pager->getLinkForPage($page) ?>">[<?= $page ?>]</a>
				<?php endif; ?>
			<?php endfor; ?>

			<?php if ($pager->getCorrentPage() != $pager->getTotalPages()) : ?>
				<a href="?<?= $pager->getLinkForPage($pager->getNextPage()) ?>">[&gt;]</a>
				<a href="?<?= $pager->getLinkForPage($pager->getTotalPages()) ?>">[&gt;&gt;]</a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>