<?php $this->render('templates/head.phtml'); ?>

	<form method="post" name="login" action="/public/login.php?go=/public/index.php">
		<input type="hidden" name="token" value="<?= htmlspecialchars($token, ENT_QUOTES) ?>">
	
		<label>
			Input your email <input type="email" name="email" pattern=".+@.+\..+" required value="<?= (null !== $loginStudentForm->getEmail()) ? htmlspecialchars($loginStudentForm->getEmail(), ENT_QUOTES) : '' ?>">
			<?= (null !== $errors->getError('login')) ? $errors->getError('login') : '' ?>
		</label>

		<label>
			Password <input type="password" name="password" pattern="(.){6,20}" required >
			<span>
				<?= (null !== $errors->getError('password')) ? $errors->getError('password') : '' ?>
			</span>
		</label>

		<input type="submit" name="input" value="input">
	</form>

<?php $this->render('templates/foot.phtml'); ?>