<?php $this->render('templates/head.phtml'); ?>

	<form method="post" name="registraion" action="/public/registration.php?go=/public/index.php">
		<!--<input type="hidden" name="id">-->

		<input type="hidden" name="token" value="<?= htmlspecialchars($token, ENT_QUOTES) ?>">
		
		<label>
			Name <input type="text" name="name" pattern="\D{1,20}" required value="<?= (null !== $registerStudentForm->getStudent()->getName()) ? htmlspecialchars($registerStudentForm->getStudent()->getName(), ENT_QUOTES) : '' ?>">
			<span>
				<?= (null !== $errors->getError('name')) ? $errors->getError('name') : '' ?>
			</span>
		</label>

		<label>
			Surname <input type="text" name="surname" pattern="\D{1,20}" required value="<?= (null !== $registerStudentForm->getStudent()->getSurname()) ? htmlspecialchars($registerStudentForm->getStudent()->getSurname(), ENT_QUOTES) : '' ?>">
			<span>
				<?= (null !== $errors->getError('surname')) ? $errors->getError('surname') : '' ?>
			</span>
		</label>

		<label>
			
			Gender <input type="radio" name="gender" value="Man" <?= ($registerStudentForm->getStudent()->getGender() == "Man") ? 'checked' : '' ?>>M <input type="radio" name="gender" value="Woman" <?= ($registerStudentForm->getStudent()->getGender() == "Woman") ? 'checked' : '' ?>>W
			<span>
				<?= (null !== $errors->getError('gender')) ? $errors->getError('gender') : '' ?>
			</span>
		</label>

		<label>
			Grup Number <input type="text" name="grupNumber" pattern="[0-9a-zA-Z]{2,5}" required  value="<?= (null !== $registerStudentForm->getStudent()->getGrupNumber()) ? htmlspecialchars($registerStudentForm->getStudent()->getGrupNumber(), ENT_QUOTES) : '' ?>">
			<span>
				<?= (null !== $errors->getError('grupNumber')) ? $errors->getError('grupNumber') : '' ?>
			</span>
		</label>

		<label>
			Email <input type="email" name="email" pattern=".+@.+\..+" required value="<?= (null !== $registerStudentForm->getStudent()->getEmail()) ? htmlspecialchars($registerStudentForm->getStudent()->getEmail(), ENT_QUOTES) : '' ?>">
			<span>
				<?= (null !== $errors->getError('email')) ? $errors->getError('email') : '' ?>
			</span>
		</label>

		<label>
			SAT Scores <input type="number" name="satScores" value="<?= (null !== $registerStudentForm->getStudent()->getSATScores()) ? htmlspecialchars($registerStudentForm->getStudent()->getSATScores(), ENT_QUOTES) : '' ?>">
			<span>
				<?= (null !== $errors->getError('satScores')) ? $errors->getError('satScores') : '' ?>
			</span>
		</label>

		<label>
			Year Of Birth <input type="text" name="yearOfBirth" pattern="\d{4}" required  value="<?= (null !== $registerStudentForm->getStudent()->getYearOfBirth()) ? htmlspecialchars($registerStudentForm->getStudent()->getYearOfBirth(), ENT_QUOTES)  : '' ?>">
			<span>
				<?= (null !== $errors->getError('yearOfBirth')) ? $errors->getError('yearOfBirth') : '' ?>
			</span>
		</label>

		<label>
			Location <input type="radio" name="location" value="local" <?= ($registerStudentForm->getStudent()->getLocation() == "local") ? 'checked' : '' ?>>Local <input type="radio" name="location" value="nonresident" <?= ($registerStudentForm->getStudent()->getLocation() == "nonresident") ? 'checked' : '' ?>>Nonresident
			<span>
				<?= (null !== $errors->getError('location')) ? $errors->getError('location') : '' ?>
			</span>
		</label>

		<label>
			Password <input type="password" name="password" pattern="(.){6,20}" <?= (!$logged) ? 'required' : '' ?>>
			<span>
				<?= (null !== $errors->getError('password')) ? $errors->getError('password') : '' ?>
			</span>
		</label>

		<label>
			Retry Password <input type="password" name="retryPassword" pattern="(.){6,20}" <?= (!$logged) ? 'required' : '' ?>>
			<span>
				<?= (null !== $errors->getError('retryPassword')) ? $errors->getError('retryPassword') : '' ?>
			</span>
		</label>

		<input type="submit" name="input" value="input">
	</form>

	<?php $this->render('templates/foot.phtml'); ?>