<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
    <link rel='stylesheet' type='text/css' href='/css/stylesheets.css'/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
</head>
<body>
		<form method="post" name="registraion" action="/public/registration.php">
			<label>
				Login <input type="text" name="login">
				<span>
					<?= isset($container['RegisterAction']->getErrors()['login']) ? $container['RegisterAction']->getErrors()['login'] : '' ?>
				</span>
			</label>

			<label>
				Password <input type="text" name="password">
				<span>
					<?= isset($container['RegisterAction']->getErrors()['password']) ? $container['RegisterAction']->getErrors()['password'] : '' ?>
				</span>
			</label>

			<label>
				Retry Password <input type="text" name="retrypassword">
				<span>
					<?= isset($container['RegisterAction']->getErrors()['retrypassword']) ? $container['RegisterAction']->getErrors()['retrypassword'] : '' ?>
				</span>
			</label>

			<input type="submit" name="someinput" value="input">
		</form>
</body>
</html>