<?php $this->render('templates/head.phtml'); ?>

<form method="get" name="search" action="/public/search.php">
	<label>
		Search <input type="text" name="query" value="<?= (isset($query)) ? htmlspecialchars($query, ENT_QUOTES) : '' ?>">
	</label>

	<input id="button" type="submit" value="input">
</form>

<?php $this->render('templates/list.phtml', compact('pager')); ?>

<?php $this->render('templates/foot.phtml'); ?>